In [20]:
from __future__ import print_function
import torch

In [21]:
x = torch.empty(5, 3)
print(x)

tensor([[3.9173e-02, 4.7429e+30, 5.5272e+31],
        [7.5338e+28, 6.1687e+16, 9.3233e-09],
        [8.0671e+17, 2.0408e-07, 2.5740e-12],
        [3.1436e-12, 2.6056e-12, 1.4588e-19],
        [3.1458e-12, 7.9309e+34, 6.0022e+31]])


In [3]:
x = torch.rand(5, 3)

In [24]:
import numpy as np
x_np = np.empty([5, 3])
print(x_np)

[[3.50338787e-316 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [4]:
print(x)

tensor([[0.8656, 0.4114, 0.0984],
        [0.1345, 0.7803, 0.4488],
        [0.4572, 0.7032, 0.2684],
        [0.7313, 0.7122, 0.6010],
        [0.3148, 0.8244, 0.8968]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])

In [7]:
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.0601,  0.6587, -1.3798],
        [-1.0547, -0.3031,  0.8661],
        [-0.7518,  0.0307, -0.8910],
        [-0.0424, -0.1952, -0.6262],
        [-0.0874,  1.5997, -1.3332]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.6950,  0.8093, -1.2406],
        [-0.2110,  0.3379,  0.9097],
        [-0.4348,  0.8652, -0.2712],
        [ 0.2494, -0.0541, -0.2109],
        [ 0.7655,  2.4651, -0.4486]])


In [12]:
print(torch.add(x, y))

tensor([[ 0.6950,  0.8093, -1.2406],
        [-0.2110,  0.3379,  0.9097],
        [-0.4348,  0.8652, -0.2712],
        [ 0.2494, -0.0541, -0.2109],
        [ 0.7655,  2.4651, -0.4486]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.6950,  0.8093, -1.2406],
        [-0.2110,  0.3379,  0.9097],
        [-0.4348,  0.8652, -0.2712],
        [ 0.2494, -0.0541, -0.2109],
        [ 0.7655,  2.4651, -0.4486]])


In [14]:
y.add_(x)
print(y)

tensor([[ 0.6950,  0.8093, -1.2406],
        [-0.2110,  0.3379,  0.9097],
        [-0.4348,  0.8652, -0.2712],
        [ 0.2494, -0.0541, -0.2109],
        [ 0.7655,  2.4651, -0.4486]])


In [15]:
print(x[:, 1])

tensor([ 0.6587, -0.3031,  0.0307, -0.1952,  1.5997])


In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1802])
0.18019689619541168


In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.1802], device='cuda:0')
tensor([1.1802], dtype=torch.float64)


In [8]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print("Index {} animal {}".format(idx + 1, animal))

Index 1 animal cat
Index 2 animal dog
Index 3 animal monkey


In [9]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print("Index ", idx + 1, " animal ", animal)

Index  1  animal  cat
Index  2  animal  dog
Index  3  animal  monkey


In [10]:
import numpy as np

In [18]:
np.random.seed(3)
a, b = np.random.randn(), np.random.randn()
print(a, b)

1.7886284734303186 0.43650985051198943
